### ISSUE TITLE
Humidity correction is commented out

### ISSUE THREAD

**Issue by danielfppps** [kromadg/soil-sensor#2]
I see in the code that the line 

soil_hum = -0.0134 * soil_hum * soil_hum + 1.6659 * soil_hum - 6.1095;

is commented out. Is there a reason why you commented out this correction? If it is not going to be used then perhaps it should be removed to avoid confusion or a note made to clarify why it is not used.

**Comment by kromadg** [comment]
There's a comment above this line notting that it is a quadratic aproximation correction of VWC. But comparing the VWC of Teros and the chinese sensor are very close, so no need to calibrate. But just in case, it's there.

Soon I will upload matlab code and some math data that I used in this project. Maybe this helps.

**Comment by kromadg** [comment]
Comments updated.
